image: registry.gitlab.com/gmullerb/basecode-ts-ionic-react/gcc-jdk-headless-xvfb-chromium-bionic:cpp.7-java.11-chromium.72-0.0.1

cache:
  key: "${CI_COMMIT_SHA}"
  untracked: true
  paths:
    - .gradle/
    - node_modules/

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export CHROME_BIN='chromium-browser'

stages:
  - inception
  - assess
  - test
  - assemble
  - e2e

create-cache:
  stage: inception
  script:
    - ./gradlew -v
    - chromium-browser --version
    - ./gradlew npmInstall
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: push
    untracked: true
    paths:
    - .gradle/
    - node_modules/

common-assess:
  stage: assess
  script:
    - ./gradlew assessCommon
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/

project-assess:
  stage: assess
  script:
    - ./gradlew assessGradle
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/

code-assess:
  stage: assess
  script:
    - ./gradlew assess
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
      - node_modules/

code-tests:
  stage: test
  script:
    - ./gradlew test
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
      - node_modules/
  artifacts:
    reports:
      junit: build/reports/tests/tests_report.xml

code-build:
  stage: assemble
  script:
    - ./gradlew assemble
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
      - node_modules/

code-e2e:
  stage: e2e
  script:
    - xvfb-run --server-args="-screen 0 1600x1200x24" ./gradlew e2e
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
      - node_modules/
